object Dependencies {
    const val ANDROID_TEST_CORE = "androidx.test:core:${Versions.ANDROID_TEST_CORE}"
    const val ANDROID_TEST_ARCH_CORE_TESTING = "androidx.arch.core:core-testing:${Versions.ANDROID_TEST_ARCH_CORE_TESTING}"
    const val ANDROID_TEST_RUNNER = "androidx.test:runner:${Versions.ANDROID_TEST_RUNNER}"
    const val ANDROID_TEST_RULES = "androidx.test:rules:${Versions.ANDROID_TEST_RULES}"
    const val ANDROID_TEST_JUNIT = "androidx.test.ext:junit:${Versions.ANDROID_TEST_JUNIT}"
    const val ANDROID_TEST_ESPRESSO_CORE = "androidx.test.espresso:espresso-core:${Versions.ANDROID_TEST_ESPRESSO}"
    const val ANDROID_ROOM_KTX = "androidx.room:room-ktx:${Versions.ANDROID_ROOM}"
    const val ANDROID_ROOM_RUNTIME = "androidx.room:room-runtime:${Versions.ANDROID_ROOM}"
    const val ANDROID_ROOM_COMPILER = "androidx.room:room-compiler:${Versions.ANDROID_ROOM}"
    const val ANDROID_ROOM_TEST = "androidx.room:room-testing:${Versions.ANDROID_ROOM}"
    const val ANDROID_APPCOMPAT = "androidx.appcompat:appcompat:${Versions.ANDROID_APPCOMPAT}"
    const val ANDROID_MATERIAL = "com.google.android.material:material:${Versions.ANDROID_MATERIAL}"
    const val ANDROID_CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout:${Versions.ANDROID_CONSTRAINT_LAYOUT}"
    const val ANDROID_RECYCLERVIEW = "androidx.recyclerview:recyclerview:${Versions.ANDROID_RECYCLERVIEW}"
    const val ANDROID_ANNOTATION = "androidx.annotation:annotation:${Versions.ANDROID_ANNOTATION}"
    const val ANDROID_VIEWPAGER2 = "androidx.viewpager2:viewpager2:${Versions.ANDROID_VIEWPAGER2}"
    const val ANDROID_KTX_CORE = "androidx.core:core-ktx:${Versions.ANDROID_KTX_CORE}"
    const val ANDROID_FRAGMENT_KTX = "androidx.fragment:fragment-ktx:${Versions.ANDROID_FRAGMENT_KTX}"
    const val ANDROID_LIFECYCLE_LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.ANDROID_LIFECYCLE_KTX}"
    const val ANDROID_LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.ANDROID_LIFECYCLE_KTX}"
    const val ANDROID_LIFECYCLE_VIEWMODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.ANDROID_LIFECYCLE_KTX}"
    const val ANDROID_LIFECYCLE_SERVICE = "androidx.lifecycle:lifecycle-service:${Versions.ANDROID_LIFECYCLE_KTX}"
    const val ANDROID_SECURITY_CRYPTO = "androidx.security:security-crypto:${Versions.ANDROID_SECURITY}"
    const val ANDROID_NAVIGATION_FRAGMENT = "androidx.navigation:navigation-fragment-ktx:${Versions.ANDROIDX_NAVIGATION}"
    const val ANDROID_NAVIGATION_UI = "androidx.navigation:navigation-ui-ktx:${Versions.ANDROIDX_NAVIGATION}"
    const val ANDROID_BIOMETRIC = "androidx.biometric:biometric:${Versions.ANDROID_BIOMETRIC}"
    //kotlin
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.KOTLIN}"
    const val KOTLIN_REFLECT = "org.jetbrains.kotlin:kotlin-reflect:${Versions.KOTLIN}"
    //coroutines
    const val COROUTINE_CORE = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.COROUTINE}"
    const val COROUTINE_ANDROID = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.COROUTINE}"
    const val COROUTINE_PLAY_SERVICES = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Versions.COROUTINE}"
    const val COROUTINE_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.COROUTINE}"
    //Test
    const val JUNIT = "junit:junit:${Versions.JUNIT}"
    const val TRUTH = "com.google.truth:truth:${Versions.TRUTH}"
    const val TRUTH_EXTENSION_JAVA8 = "com.google.truth.extensions:truth-java8-extension:${Versions.TRUTH}"
    const val ROBOLECTRIC = "org.robolectric:robolectric:${Versions.ROBOLECTRIC}"
    const val MOCKK = "io.mockk:mockk:${Versions.MOCKK}"
    const val MOCKK_ANDROID = "io.mockk:mockk-android:${Versions.MOCKK}"
    // Android Compose
    const val ANDROID_COMPOSE_UI = "androidx.compose.ui:ui:${Versions.ANDROID_COMPOSE}"
    const val ANDROID_COMPOSE_MATERIAL = "androidx.compose.material:material:${Versions.ANDROID_COMPOSE}"
    const val ANDROID_COMPOSE_UI_TOOLS = "androidx.compose.ui:ui-tooling:${Versions.ANDROID_COMPOSE}"
    const val ANDROID_COMPOSE_UI_TEST_MANIFEST = "androidx.compose.ui:ui-test-manifest:${Versions.ANDROID_COMPOSE}"
    const val ANDROID_COMPOSE_UI_TOOLS_PREVIEW = "androidx.compose.ui:ui-tooling-preview:${Versions.ANDROID_COMPOSE}"
    const val ANDROID_COMPOSE_RUNTIME = "androidx.compose.runtime:runtime:${Versions.ANDROID_COMPOSE}"
    const val ANDROID_COMPOSE_RUNTIME_LIVEDATA = "androidx.compose.runtime:runtime-livedata:${Versions.ANDROID_COMPOSE}"
    const val ANDROID_COMPOSE_ACTIVITY = "androidx.activity:activity-compose:${Versions.ANDROID_COMPOSE_ACTIVITY}"
    const val ANDROID_COMPOSE_CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout-compose:${Versions.ANDROID_COMPOSE_CONSTRAINT_LAYOUT}"
    const val ANDROID_COMPOSE_JUNIT = "androidx.compose.ui:ui-test-junit4:${Versions.ANDROID_COMPOSE}"
}