object Versions {
    const val ANDROID_TEST_CORE = "1.3.0"
    const val ANDROID_TEST_RUNNER = "1.3.0"
    const val ANDROID_TEST_RULES = "1.3.0"
    const val ANDROID_TEST_JUNIT = "1.1.2"
    const val ANDROID_TEST_ARCH_CORE_TESTING = "2.1.0"
    const val ANDROID_TEST_ESPRESSO = "3.3.0"
    const val ANDROID_ROOM = "2.3.0"
    const val ANDROID_APPCOMPAT = "1.4.1"
    const val ANDROID_MATERIAL = "1.6.0"
    const val ANDROID_CONSTRAINT_LAYOUT = "2.1.1"
    const val ANDROID_RECYCLERVIEW = "1.2.1"
    const val ANDROID_ANNOTATION = "1.3.0"
    const val ANDROID_VIEWPAGER2 = "1.0.0"
    const val ANDROID_KTX_CORE = "1.7.0"
    const val ANDROID_FRAGMENT_KTX = "1.4.1"
    const val ANDROID_LIFECYCLE_KTX = "2.4.1"
    const val ANDROID_BROWSER_HELPER = "1.3.2"
    const val ANDROID_SECURITY = "1.0.0"
    const val ANDROIDX_NAVIGATION = "2.3.5"
    const val ANDROID_BIOMETRIC = "1.1.0"
    // Android Compose
    const val ANDROID_COMPOSE = "1.1.1"
    const val ANDROID_COMPOSE_ACTIVITY = "1.4.0"
    const val ANDROID_COMPOSE_CONSTRAINT_LAYOUT = "1.0.1"
    // Kotlin
    const val KOTLIN = "1.6.10"
    const val COROUTINE = "1.6.1"
    // Test
    const val JUNIT = "4.13.2"
    const val TRUTH = "1.1.2"
    const val ROBOLECTRIC = "4.4.1"
    const val MOCKK = "1.10.2"
}